defaults:
  - kernel: kermut
  - data: proteingym
  - _self_
  - override hydra/job_logging: disabled

dataset: ???
split: ???
test_index: -1
dataset_by_name: false
standardize: true
sequence_col: mutated_sequence
target_col: DMS_score

seed: 2024
overwrite: false
use_gpu: true
progress_bar: true

optim:
  n_steps: 150
  lr: 0.1
  progress_bar: false

hydra:
  output_subdir: null
  job:
    chdir: false
  run:
    dir: .
  sweep:
    dir: .
    subdir: .

  